# Generated by Django 3.0.5 on 2021-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(default=None, max_length=100)),
                ('user_phone', models.BigIntegerField()),
                ('user_password', models.TextField()),
                ('user_aadhaar', models.BigIntegerField()),
                ('user_address', models.TextField()),
                ('user_dob', models.DateField()),
                ('user_email', models.TextField()),
                ('user_gender', models.CharField(max_length=6)),
                ('user_status', models.CharField(default='new', max_length=20)),
                ('user_joined_date', models.DateField()),
                ('user_photo', models.ImageField(default='photo', upload_to='user_photos')),
                ('user_aadhar_photo', models.ImageField(default='photo', upload_to='user_aadhaar_photo')),
            ],
        ),
    ]
