# Generated by Django 3.0.5 on 2021-11-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='image',
            field=models.ImageField(upload_to='city_images'),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='room_type',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Double'), ('3', 'Triple'), ('4', 'Quad'), ('5', 'Queen'), ('6', 'King'), ('7', 'Twin'), ('8', 'Hollywood-Twin'), ('9', 'Studio'), ('10', 'Suite')], default='1', max_length=30),
        ),
    ]
