# Generated by Django 3.0.5 on 2021-11-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20211105_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_type',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Queen', 'Queen'), ('King', 'King'), ('Twin', 'Twin'), ('Hollywood-Twin', 'Hollywood-Twin'), ('Studio', 'Studio'), ('Suite', 'Suite')], default='Single', max_length=30),
        ),
    ]
