# Generated by Django 3.0.5 on 2021-11-05 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20211105_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_user', models.CharField(default='Admin', max_length=30)),
                ('room_id', models.PositiveIntegerField()),
                ('room_taking_date', models.DateField()),
                ('room_leaving_date', models.DateField()),
                ('room_booking_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='room_type',
            name='room_rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room_type',
            name='room_user',
            field=models.CharField(default='Admin', max_length=30),
        ),
    ]
