# Generated by Django 3.0.5 on 2021-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=20)),
                ('task', models.TextField()),
                ('accomplished', models.BooleanField(default=False)),
            ],
        ),
    ]
